// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxhwfjukodlphnhmylsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4aHdmanVrb2RscGhuaG15bHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDQ1NzcsImV4cCI6MjA1ODgyMDU3N30.DGtzBpkHjmJ8q4EVznyu5_6IriGoQ51yWzk2sVQk3zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);